In [2]:
import numpy as np

In [7]:
arr = np.random.randn(5, 4)
arr

array([[-0.20777346, -0.94647089, -0.55668635,  0.80778288],
       [ 1.18418777,  0.32323294, -0.02367937, -0.44346034],
       [ 0.04248675,  0.85629536,  0.28666423,  0.18634518],
       [-0.49018005,  0.89327023,  2.41110123,  1.70214065],
       [ 0.5056873 ,  0.56025626, -1.55017865, -0.1490987 ]])

`sum` sonlarning yig'indisi uchun ishlatiladi

In [8]:
arr.sum()    # umumiy sonlar yig'indisi uchun sum

5.3919229745747375

In [9]:
arr.sum(axis=1)  # qator yig'indi

array([-0.90314782,  1.04028099,  1.37179152,  4.51633207, -0.63333379])

In [10]:
arr.sum(axis=0)   # ustun yig'indi

array([1.03440831, 1.6865839 , 0.5672211 , 2.10370966])

### `mean` <h5> uslubi sonning o'rta arifmetigini topib beradi </h5>

In [12]:
data = np.arange(6)
data

array([0, 1, 2, 3, 4, 5])

In [14]:
mean = np.sum(data)/len(data)
mean

2.5

In [15]:
np.mean(data)

2.5

In [16]:
data.mean()

2.5

In [18]:
arr

array([[-0.20777346, -0.94647089, -0.55668635,  0.80778288],
       [ 1.18418777,  0.32323294, -0.02367937, -0.44346034],
       [ 0.04248675,  0.85629536,  0.28666423,  0.18634518],
       [-0.49018005,  0.89327023,  2.41110123,  1.70214065],
       [ 0.5056873 ,  0.56025626, -1.55017865, -0.1490987 ]])

In [17]:
np.mean(arr)

0.2695961487287369

In [19]:
np.mean(arr, axis=1)

array([-0.22578696,  0.26007025,  0.34294788,  1.12908302, -0.15833345])

In [21]:
np.mean(arr, axis=0)

array([0.20688166, 0.33731678, 0.11344422, 0.42074193])

### `cumsum` <h5> uslubi sonning yig'iluvchi yig'indi topib beradi </h5>

In [22]:
data

array([0, 1, 2, 3, 4, 5])

In [23]:
data.cumsum()

array([ 0,  1,  3,  6, 10, 15])