In [3]:
import numpy as np

In [5]:
arr = np.random.randn(4)
arr

array([-2.4418595 ,  0.28610148,  0.43318913, -0.92115489])

### `sort` funksiyasi

In [7]:
sorted_arr = np.sort(arr)
sorted_arr

array([-2.4418595 , -0.92115489,  0.28610148,  0.43318913])

In [9]:
arr.sort()   # 2-usul
arr

array([-2.4418595 , -0.92115489,  0.28610148,  0.43318913])

<h4>Teskari tartiblash</h4>

In [10]:
rev_arr = -np.sort(-arr)
rev_arr

array([ 0.43318913,  0.28610148, -0.92115489, -2.4418595 ])

In [12]:
arr2d = np.random.randn(2, 4)
arr2d

array([[ 0.67598613, -0.01784671,  1.29514727,  1.46590296],
       [-1.98765831, -0.52352807, -1.73196589,  0.30930433]])

In [13]:
row_srt = np.sort(arr2d, axis=0) #arr2d qator bo'yicha tartiblangan ko'rinishi
row_srt

array([[-1.98765831, -0.52352807, -1.73196589,  0.30930433],
       [ 0.67598613, -0.01784671,  1.29514727,  1.46590296]])

In [14]:
col_srt = np.sort(arr2d, axis=1)
col_srt

array([[-0.01784671,  0.67598613,  1.29514727,  1.46590296],
       [-1.98765831, -1.73196589, -0.52352807,  0.30930433]])