In [1]:
import numpy as np

In [2]:
x = np.array ([[1., 2., 3., ],[4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
y = np.array([[5., 5., 5.], [4., 4., 4]])
y

array([[5., 5., 5.],
       [4., 4., 4.]])

In [4]:
x+y

array([[ 6.,  7.,  8.],
       [ 8.,  9., 10.]])

In [5]:
y-x

array([[ 4.,  3.,  2.],
       [ 0., -1., -2.]])

In [8]:
x*5
x**10

array([[1.0000000e+00, 1.0240000e+03, 5.9049000e+04],
       [1.0485760e+06, 9.7656250e+06, 6.0466176e+07]])