In [1]:
import numpy as np

In [7]:
arr = np.arange(10, 100, 10)

In [8]:
arr[2]

30

In [11]:
arr[3:5]

array([40, 50])

In [14]:
sliced_arr = arr[3:5]
sliced_arr[:] = 0
sliced_arr

array([0, 0])

In [16]:
arr1 = np.arange(10, 100, 10)
arr1 

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
sliced_arr1 = arr1[3:5].copy()  # ko'chirib olingan arrayda asosiy arrayga tasir bermaydi
sliced_arr1[:] = 0
sliced_arr1

array([0, 0])

In [22]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

<h5> 2D MASSIVLAR <h5>

In [26]:
arr2d = np.array([[1,2,3,4], [5,6,7,8], [1,2,3,4]])     # 3x3 olchamli massiv
arr2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [28]:
arr2d.ndim

2

In [29]:
arr2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [30]:
arr2d[1,1]

6

In [32]:
arr2d[2,3]

4

<h5>2D massivdan bir nechta element olish</h5>

In [37]:
sl_arr = arr2d[2, 2:4]  # sonlar 0, 1, 2, 3, 4 qilib sanalgani uchun 2:4 bular 3,4 sonalridir
sl_arr

array([3, 4])

In [38]:
sl_arr2 = arr2d[2, 2:]  # sonlar 0, 1, 2, 3, 4 qilib sanalgani uchun 2:4 bular 3,4 sonalridir
sl_arr2

array([3, 4])