In [1]:
import numpy as np

In [2]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [3]:
kond = np.array([True, False, True, True, False])

<h5>Agar kond = True ---> xarr  YOKI agar kond = False ----> yarr</h5>

In [5]:
natija = np.where(kond, xarr, yarr)
natija

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [7]:
arr = np.random.randn(4,4)
arr

array([[ 1.28808818,  1.68199039,  1.76547034, -0.61982636],
       [ 0.13604946, -1.11760303,  1.50359974, -0.99469316],
       [ 0.94628238, -0.3576776 ,  0.03784755,  0.84219326],
       [ 0.34560939, -0.43534875, -0.72144102,  0.31157803]])

<h4>Agar arr < 0 dan kichik bo'lsa uni -2 aylatiradi, aks holda musbat bo'lsa uni 2 o'zgartiriladi </h4>

In [9]:
natijalar = np.where(arr<0, -2, 2)
natijalar

array([[ 2,  2,  2, -2],
       [ 2, -2,  2, -2],
       [ 2, -2,  2,  2],
       [ 2, -2, -2,  2]])