In [13]:
import numpy as np

In [14]:
data1 = [3,4,5,3,2,5,7,8] # list 
arr1 = np.array(data1) # array1

In [15]:
arr1

array([3, 4, 5, 3, 2, 5, 7, 8])

In [16]:
data2 = (43,343,35,4546,57,676,8,45)
arr2 = np.array(data2) 

In [17]:
arr2

array([  43,  343,   35, 4546,   57,  676,    8,   45])

In [18]:
arr2.ndim

1

In [19]:
arr1.ndim

1

In [26]:
data3 = [[3,4,5,6,5],[3,4,3,5,1]]  # list ichifagi list (nested)
arr3 = np.array(data3)

In [28]:
arr3

array([[3, 4, 5, 6, 5],
       [3, 4, 3, 5, 1]])

In [29]:
arr3.ndim

2

In [31]:
arr3.shape   # qator va ustunlar sonini ko'rsatadi ( qator = 2,  ustun = 5)

(2, 5)

In [32]:
arr3.size  # elementlar sonini ko'rsatadi 

10

In [36]:
arr4 = np.zeros((2, 6))
arr4 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [37]:
arr5 = np.ones((2, 6))
arr5

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
arr6 = np.arange(20)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
arr7 = np.arange(1, 90, 10)
arr7 

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81])