In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('data', arr)

In [5]:
arr2 = np.load('data.npy')
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr3 = np.arange(20)

In [8]:
np.savez('arrays', a=arr, b=arr2)  #argument ko'rimishida Arraylarni berish lozim

In [9]:
arrays = np.load('arrays.npz')

In [12]:
arrays['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.savez_compressed('array_comp.npz', a=arr, b=arr2) # bu katta arraylar uchun ishlatiladi