In [5]:
import numpy as np

In [9]:
# ismlar
names = np.array (['hasan', 'husan', 'mirzabek', 'ahmad', 'karim', 'holiq', 'hasan', 'husan'])
names

array(['hasan', 'husan', 'mirzabek', 'ahmad', 'karim', 'holiq', 'hasan',
       'husan'], dtype='<U8')

In [16]:
# data = ma'lumot
data = np.random.randn(8, 5)
data

array([[ 0.22175626,  1.38733524,  1.5834049 ,  0.70235953,  1.57324006],
       [-1.57313118, -0.25227514,  0.16461783,  1.7711997 , -1.42898866],
       [ 0.79268002,  0.82305078,  1.15934745,  0.62575081,  0.30051766],
       [ 0.45536853,  0.46787218, -1.0408907 , -1.74200385,  0.40703703],
       [-0.29795567,  0.3769657 , -0.19265621, -0.58894982,  1.21663982],
       [-0.14215569,  2.57700327,  0.02509215,  0.5437937 , -1.12958084],
       [ 0.00688399,  0.78201666, -0.17071109, -0.8624003 ,  1.69908423],
       [ 1.35890871, -1.67878298,  0.1865147 , -0.61481472, -0.6930655 ]])

In [17]:
names == 'hasan'

array([ True, False, False, False, False, False,  True, False])

In [18]:
data[names == 'hasan']

array([[ 0.22175626,  1.38733524,  1.5834049 ,  0.70235953,  1.57324006],
       [ 0.00688399,  0.78201666, -0.17071109, -0.8624003 ,  1.69908423]])

In [27]:
data[names == 'hasan' ]

array([], shape=(0, 5), dtype=float64)

In [28]:
data[names != 'hasan']

array([[-1.57313118, -0.25227514,  0.16461783,  1.7711997 , -1.42898866],
       [ 0.79268002,  0.82305078,  1.15934745,  0.62575081,  0.30051766],
       [ 0.45536853,  0.46787218, -1.0408907 , -1.74200385,  0.40703703],
       [-0.29795567,  0.3769657 , -0.19265621, -0.58894982,  1.21663982],
       [-0.14215569,  2.57700327,  0.02509215,  0.5437937 , -1.12958084],
       [ 1.35890871, -1.67878298,  0.1865147 , -0.61481472, -0.6930655 ]])

In [31]:
data [~(names == 'hasan')]

array([[-1.57313118, -0.25227514,  0.16461783,  1.7711997 , -1.42898866],
       [ 0.79268002,  0.82305078,  1.15934745,  0.62575081,  0.30051766],
       [ 0.45536853,  0.46787218, -1.0408907 , -1.74200385,  0.40703703],
       [-0.29795567,  0.3769657 , -0.19265621, -0.58894982,  1.21663982],
       [-0.14215569,  2.57700327,  0.02509215,  0.5437937 , -1.12958084],
       [ 1.35890871, -1.67878298,  0.1865147 , -0.61481472, -0.6930655 ]])

In [32]:
print(names)
print(data)

['hasan' 'husan' 'mirzabek' 'ahmad' 'karim' 'holiq' 'hasan' 'husan']
[[ 0.22175626  1.38733524  1.5834049   0.70235953  1.57324006]
 [-1.57313118 -0.25227514  0.16461783  1.7711997  -1.42898866]
 [ 0.79268002  0.82305078  1.15934745  0.62575081  0.30051766]
 [ 0.45536853  0.46787218 -1.0408907  -1.74200385  0.40703703]
 [-0.29795567  0.3769657  -0.19265621 -0.58894982  1.21663982]
 [-0.14215569  2.57700327  0.02509215  0.5437937  -1.12958084]
 [ 0.00688399  0.78201666 -0.17071109 -0.8624003   1.69908423]
 [ 1.35890871 -1.67878298  0.1865147  -0.61481472 -0.6930655 ]]


In [33]:
mask = (names == 'hasan') | (names == 'husan')
mask

array([ True,  True, False, False, False, False,  True,  True])

In [34]:
data[mask]

array([[ 0.22175626,  1.38733524,  1.5834049 ,  0.70235953,  1.57324006],
       [-1.57313118, -0.25227514,  0.16461783,  1.7711997 , -1.42898866],
       [ 0.00688399,  0.78201666, -0.17071109, -0.8624003 ,  1.69908423],
       [ 1.35890871, -1.67878298,  0.1865147 , -0.61481472, -0.6930655 ]])

In [35]:
data

array([[ 0.22175626,  1.38733524,  1.5834049 ,  0.70235953,  1.57324006],
       [-1.57313118, -0.25227514,  0.16461783,  1.7711997 , -1.42898866],
       [ 0.79268002,  0.82305078,  1.15934745,  0.62575081,  0.30051766],
       [ 0.45536853,  0.46787218, -1.0408907 , -1.74200385,  0.40703703],
       [-0.29795567,  0.3769657 , -0.19265621, -0.58894982,  1.21663982],
       [-0.14215569,  2.57700327,  0.02509215,  0.5437937 , -1.12958084],
       [ 0.00688399,  0.78201666, -0.17071109, -0.8624003 ,  1.69908423],
       [ 1.35890871, -1.67878298,  0.1865147 , -0.61481472, -0.6930655 ]])

In [36]:
data[data<0] = 1        # noldan kichik barcha sonlarni 1 o'zgaritirib qo'yiladi
data

array([[0.22175626, 1.38733524, 1.5834049 , 0.70235953, 1.57324006],
       [1.        , 1.        , 0.16461783, 1.7711997 , 1.        ],
       [0.79268002, 0.82305078, 1.15934745, 0.62575081, 0.30051766],
       [0.45536853, 0.46787218, 1.        , 1.        , 0.40703703],
       [1.        , 0.3769657 , 1.        , 1.        , 1.21663982],
       [1.        , 2.57700327, 0.02509215, 0.5437937 , 1.        ],
       [0.00688399, 0.78201666, 1.        , 1.        , 1.69908423],
       [1.35890871, 1.        , 0.1865147 , 1.        , 1.        ]])