In [1]:
import numpy as np

In [14]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
a.T

array([[0, 2, 4],
       [1, 3, 5]])

In [10]:
a.swapaxes(0, 1)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [11]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
np.dot(a, a.T)

array([[ 5, 14],
       [14, 50]])

In [13]:
np.matmul(a, a.T)

array([[ 5, 14],
       [14, 50]])