In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`Urany` funksiyalar yani bitta argument oladi (arg1)

`sqrt` massivning xar bir elementini kvadrat ildizni qaytaradi

In [4]:
np.sqrt(arr) # arr nomli massivning barcha elementlaridan kv ildizni qaytaradi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

`square` massivning xar bir elementini kvadratga oshiradi

In [5]:
np.square(arr) # arr nomli massivning barcha elementlarini kvadratga oshiradi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

`exp` massivning xar bir elementini eksponentini qaytaradi

In [10]:
np.exp(arr) # arr nomli massivning barcha elemntlarini eksponentini qaytaradi

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

`log` massivning xar bir logorifmini hisoblaydi

In [8]:
np.log(arr[1:]) # arr nomli massivning 0-elementdan tashqari barcha elementlarini logarifmini hisoblaydi (loge)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

`modf` bu funksiya haqiqiy sonlarni butun va qoldiq qismlarini ajratib beruvchi funksiya

In [11]:
arr1 = np.random.randn(6) # 6 ta elementdan iborat taxminiy qiymatlarga ega massiv
arr1

array([ 0.05083832, -0.87935673, -1.24552952,  0.49405693,  0.1681008 ,
        0.91438399])

In [12]:
qoldiq, butun = np.modf(arr1) # arr1 ning elementlarini qoldiq va butun qismlarini ikkita massivga ajratadi

In [13]:
print(qoldiq)
print(butun)

[ 0.05083832 -0.87935673 -0.24552952  0.49405693  0.1681008   0.91438399]
[ 0. -0. -1.  0.  0.  0.]


`sign` funkisyasi massiv elementlarini qiymati manfiy bo'lsa -1 
va aksincha musbat bo'lsa 1 ni qaytaradi

In [15]:
np.sign(arr1) # arr1 massivining elementlari ishoralarini "-1" va "1" ko'rinishida qaytaradi

array([ 1., -1., -1.,  1.,  1.,  1.])

`isnan` massivning elementlarida NaN ma'lumoti bo'lsa True qaytaradi va aksincha esa False qaytaradi

In [16]:
arr1

array([ 0.05083832, -0.87935673, -1.24552952,  0.49405693,  0.1681008 ,
        0.91438399])

In [17]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [18]:
arr1[0] = np.NaN # 0- elementimizni nan ga almashtirish

In [19]:
arr1

array([        nan, -0.87935673, -1.24552952,  0.49405693,  0.1681008 ,
        0.91438399])

In [20]:
np.isnan(arr1)

array([ True, False, False, False, False, False])

Binary funksiyalar (ikkita argument qabul qiluvchi funkisya)
`add`, `multiply`, `maximum` funksiyalarini ko'rib chiqamiz
`add` ikkita massivning mos elementlarini qo'shadi

In [21]:
# 2 ta massivni yaratib olamiz
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)

In [22]:
arr2
arr3

array([ 0.98243   ,  0.43604515,  0.75268075,  0.09256417,  0.72386897,
       -0.08726899])

In [23]:
np.add(arr2, arr3)

array([ 2.72041753,  0.19359167,  0.57576811,  1.29602486,  0.83770098,
       -1.4945216 ])

In [24]:
arr2 + arr3 # arr2 va arr3 ning elementlarini mos ravishda qo'shib beradi

array([ 2.72041753,  0.19359167,  0.57576811,  1.29602486,  0.83770098,
       -1.4945216 ])

`multiply` ikkita massivning mos elementlarini ko'paytiradi

In [25]:
np.multiply(arr2, arr3) # arr2 va arr3 ning mos elementlarini ko'paytiradi

array([ 1.70745109, -0.10572067, -0.13315873,  0.11139734,  0.08239946,
        0.12280951])

`maximum` ikkita massivning elementlarin taqqoslab ulardan kattasining qiymatini qaytaradi

In [26]:
np.maximum(arr2, arr3) # arr2 va arr3 larning elementlarin taqqoslab, kattasining elementini qaytaradi

array([ 1.73798754,  0.43604515,  0.75268075,  1.20346069,  0.72386897,
       -0.08726899])