In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5], dtype=np.float64) # bu numpy float64 massiv
arr1

array([1., 2., 3., 4., 5.])

In [3]:
arr2 = np.array([1,2,3,4,5], dtype=np.int32) # bu integer32 massiv 
arr2

array([1, 2, 3, 4, 5], dtype=int32)

In [4]:
arr1.dtype  # massivni turini ko'rish uchun

dtype('float64')

In [5]:
arr2.dtype 

dtype('int32')

In [7]:
arr = np.array([1,2,3,4,5]) # agar massivga turini bermasa va int bolsa u avtomatik int64 bo'ladi.
arr.dtype

dtype('int64')

In [9]:
float_array = arr.astype(np.float64)  # arr.astype orqali ma'lumot turini o'zgartirishimiz mumkin
float_array.dtype

dtype('float64')

In [10]:
data = np.array([2.3, 4.3, 6.7, 3.5, 6]) #avtomatik ravishda bu float64 bo'ladi
data

array([2.3, 4.3, 6.7, 3.5, 6. ])

In [13]:
int_data = data.astype(np.int64)   # ma'lumot integerga o'zgaradi, ammo faqat butun qismlari olinadi
int_data

array([2, 4, 6, 3, 6])

In [14]:
int_data.dtype

dtype('int64')